import {groups,prototypes,indices,beetleScores,criteria,originalWeights,exampleScores,comparisonScores,nearest,ahp,score,sweep,traitKey} from './model.js';
import {colors,radar,heatmap,donut,distanceChart} from './charts.js';
const $=id=>document.getElementById(id);let x=beetleScores.slice();let matrix=originalWeights.map(a=>originalWeights.map(b=>a/b)),scores=exampleScores.slice(),comp=comparisonScores.slice();
const fmt=n=>n.toFixed(3),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setTab(name){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===name));document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-pressed',b.dataset.tab===name);});}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
function legends(id,names,cs){$(id).innerHTML=names.map((n,i)=>`<span><i style="background:${cs[i]}"></i>${esc(n)}</span>`).join('');}
function bars(id,items,max){$(id).innerHTML=items.map(a=>`<div class="distance-row"><span>${esc(a.label)}</span><div class="bar-track"><div class="bar" style="background:${a.color};width:${100*a.value/max}%"></div></div><span class="numeric">${fmt(a.value)}</span></div>`).join('');}
$('features').innerHTML=x.map((v,i)=>`<div class="feature-row"><label for="f${i}"><span class="index-number">0${i+1}</span>${indices[i].name}</label><div class="feature-controls"><input aria-label="${indices[i].name} score slider" id="r${i}" type="range" min="0" max="5" step="0.1" value="${v}"><input id="f${i}" aria-label="${indices[i].name} score" type="number" min="0" max="5" step="0.1" value="${v}"></div></div>`).join('');
$('scoring-key').innerHTML=indices.map((a,i)=>`<div class="scoring-key-row"><strong>${i+1}. ${esc(a.name)}</strong><span>${esc(a.key)}</span></div>`).join('');
function setVector(v){x=v.slice();x.forEach((a,i)=>{$('f'+i).value=a;$('r'+i).value=a;});updateKNN();}
for(let i=0;i<7;i++)for(const prefix of ['r','f'])$(prefix+i).oninput=e=>{const v=Number(e.target.value);if(e.target.value===''||!Number.isFinite(v)||v<0||v>5){e.target.setCustomValidity('Use a finite value between 0 and 5.');return;}e.target.setCustomValidity('');x[i]=v;$('f'+i).value=v;$('r'+i).value=v;updateKNN();};
$('preset').onchange=e=>setVector(e.target.value==='exp4'?[4,2.5,3,1,1,4,2]:e.target.value==='beetle'?beetleScores:prototypes[+e.target.value]);$('reset').onclick=()=>{$('preset').value='beetle';setVector(beetleScores);};
function updateRadar(){const selected=$('radar-reference').value||'nearest',r=nearest(x),i=selected==='nearest'?groups.indexOf(r[0].group):Number(selected);$('profile').innerHTML=radar(x,prototypes[i],indices.map(a=>a.short),colors[i]);legends('profile-legend',['Your input',groups[i]+' reference'],['#e7f9ff',colors[i]]);}
$('radar-reference').onchange=updateRadar;
function updateKNN(){const r=nearest(x);$('prediction').textContent=r[0].group;$('nearest-distance').textContent=fmt(r[0].distance);$('margin').textContent=`Reference ${r[0].id} · gap to next match ${fmt(r[1].distance-r[0].distance)}`;bars('distances',r.map(a=>({label:a.group,value:a.distance,color:colors[groups.indexOf(a.group)]})),Math.max(...r.map(a=>a.distance),1));
 updateRadar();$('reference-table').innerHTML=heatmap([...prototypes.map((p,i)=>({name:groups[i]+' · '+'ABCD'[i],values:p})),{name:'Rhinoceros beetle · sample',values:beetleScores},{name:'Your input · live',values:x}],indices);updateSweep();}
function updateKey(){const legs=+$('legs').value,ant=+$('antennae').value,seg=$('segments').value;if(!Number.isInteger(legs)||legs<0||legs>400){$('legs').setCustomValidity('Use a whole number from 0 to 400.');return;}$('legs').setCustomValidity('');const r=traitKey(legs,ant,seg);$('key-result').textContent=r;$('key-explanation').textContent=r==='Indeterminate'?'These traits do not resolve a group in this simplified key. Check the specimen and use a fuller identification reference.':'A broad-group match from the entered traits, not species-level identification.';$('key-trace').innerHTML=[['01','Legs',legs],['02','Antennae',`${ant} pair(s)`],['03','Body organization',$('segments').selectedOptions[0].text]].map(a=>`<div class="trace-step"><span>${a[0]}</span>${a[1]}: <strong>${esc(a[2])}</strong></div>`).join('');}
['legs','antennae','segments'].forEach(id=>$(id).oninput=updateKey);
function initAHP(){let html='';for(let i=0;i<4;i++)for(let j=i+1;j<4;j++)html+=`<div class="pair-row"><label for="p${i}${j}">${criteria[i]} / ${criteria[j]}</label><input id="p${i}${j}" type="number" min="0.01" max="100" step="any" value="${matrix[i][j].toFixed(5)}"></div>`;$('pairwise-controls').innerHTML=html;
 for(let i=0;i<4;i++)for(let j=i+1;j<4;j++)$('p'+i+j).oninput=e=>{const v=Number(e.target.value);if(!Number.isFinite(v)||v<=0||v>100){e.target.setCustomValidity('Use a positive number up to 100.');return;}e.target.setCustomValidity('');matrix[i][j]=v;matrix[j][i]=1/v;updateAHP();};}
$('scores').innerHTML=`<div class="score-row score-head"><span>Criterion</span><span>Beetle</span><span>Compare</span></div>`+criteria.map((c,i)=>`<div class="score-row"><span>${c}</span><input id="s${i}" aria-label="${c} beetle example" type="number" min="0" max="10" step="0.1" value="${scores[i]}"><input id="c${i}" aria-label="${c} comparison example" type="number" min="0" max="10" step="0.1" value="${comp[i]}"></div>`).join('');
for(let i=0;i<4;i++)for(const [prefix,array] of [['s',scores],['c',comp]])$(prefix+i).oninput=e=>{const v=+e.target.value;if(e.target.value===''||!Number.isFinite(v)||v<0||v>10){e.target.setCustomValidity('Use a score from 0 to 10.');return;}e.target.setCustomValidity('');array[i]=v;updateAHP();};
function updateAHP(){const a=ahp(matrix);$('matrix').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Ratio</th>${['Eco','Origin','Spread','Econ'].map(n=>`<th>${n}</th>`).join('')}</tr></thead><tbody>${matrix.map((row,i)=>`<tr><th>${['Eco','Origin','Spread','Econ'][i]}</th>${row.map(v=>`<td>${v.toFixed(2)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;$('weight-donut').innerHTML=donut(a.weights,criteria);$('weights').innerHTML=a.weights.map((v,i)=>`<div class="weight-item"><span><i style="background:${colors[i]}"></i>${criteria[i]}</span><strong>${(v*100).toFixed(1)}%</strong><div class="weight-track"><div style="width:${v*100}%;background:${colors[i]}"></div></div></div>`).join('');$('consistency').classList.toggle('warn',a.cr>=.1);$('consistency').innerHTML=`<span>CR <strong>${a.cr.toFixed(4)}</strong></span><span>${a.cr<.1?'Below conventional 0.10 threshold':'Revisit pairwise judgments'}</span>`;const b=score(scores,a.weights),c=score(comp,a.weights);bars('score-chart',[{label:'Beetle example',value:b,color:'#297953'},{label:'Comparison',value:c,color:'#8a68ae'}],10);$('score-comparison').textContent=`Example score difference: ${(b-c).toFixed(3)}. ${b>c?'Beetle example scores higher.':b<c?'Comparison scores higher.':'Scores are equal.'}`;}
$('reset-ahp').onclick=()=>{matrix=originalWeights.map(a=>originalWeights.map(b=>a/b));scores.splice(0,4,...exampleScores);comp.splice(0,4,...comparisonScores);for(let i=0;i<4;i++){$('s'+i).value=scores[i];$('c'+i).value=comp[i];}initAHP();updateAHP();};
$('sweep-feature').innerHTML=indices.map((a,i)=>`<option value="${i}">${i+1} · ${a.name}</option>`).join('');legends('sweep-legend',groups,colors);
function updateSweep(){const feature=+$('sweep-feature').value,delta=+$('delta').value,r=sweep(x,feature,delta);$('delta-value').textContent=delta.toFixed(1);$('stability').textContent=(r.unchanged*100).toFixed(1)+'%';$('sweep-summary').textContent=`Baseline: ${r.base} · current input [${x.join(', ')}]`;const xmin=x[feature]-delta,xmax=x[feature]+delta,ymax=Math.max(1,...r.points.flatMap(p=>p.distances))*1.07;
 $('sweep-chart').innerHTML=distanceChart(groups.map((g,i)=>({name:g,color:colors[i],points:r.points.map(p=>[p.value,p.distances[i]])})),Array.from({length:5},(_,i)=>({value:xmin+(xmax-xmin)*i/4,label:(xmin+(xmax-xmin)*i/4).toFixed(1)})),{xMin:xmin,xMax:xmax,yMax:ymax,xTitle:indices[feature].name});$('class-strip').innerHTML=r.points.map(p=>`<span style="background:${colors[groups.indexOf(p.group)]};flex:1" title="${p.value.toFixed(2)}: ${p.group}"></span>`).join('');$('class-strip').setAttribute('aria-label',`Predictions across the interval: ${[...new Set(r.points.map(p=>p.group))].join(', ')}`);$('sweep-min').textContent=xmin.toFixed(2);$('sweep-max').textContent=xmax.toFixed(2);}
['sweep-feature','delta'].forEach(id=>$(id).oninput=updateSweep);
const sources=[
 ['Arthropod Classifier.py','Morphological key','Python · trait-based guide'],
 ['(KNN) Arthropod Classifier (Last version!!) [Experiment2].py','KNN classifier','Python · four reference groups'],
 ['Rhinoceos Beetles AHP.py','AHP score comparison','Python · criterion scores'],
 ['Sensitivity Analysis Arthropod Classifier (Last version!!) [Experiment4].py','Sensitivity example','Python · modified sample']
];
$('source-list').innerHTML=sources.map(([name,title,description])=>`<div class="source-item"><a href="downloads/original/${encodeURIComponent(name)}" download>${esc(title)}</a><span>${esc(description)}</span></div>`).join('');
initAHP();updateAHP();updateKNN();updateKey();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_classifier_values',description:'Set seven arthropod scoring indices in the visible nearest-neighbor comparison and return distances.',inputSchema:{type:'object',properties:{values:{type:'array',items:{type:'number',minimum:0,maximum:5},minItems:7,maxItems:7}},required:['values'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Array.isArray(input.values)||input.values.length!==7||input.values.some(v=>!Number.isFinite(v)||v<0||v>5))throw Error('Provide seven finite numbers from 0 to 5.');setVector(input.values);setTab('knn');return {matches:nearest(x)};}})).catch(()=>{});}catch{}}
